# Generated by Django 3.0.7 on 2020-08-10 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
